// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:20008c16-b9b7-4ef4-b2fc-aea20862328f",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_VYLstuuWv",
    "aws_user_pools_web_client_id": "4pio285oar3rlaohtq5nb0rfoe",
    "oauth": {},
    "aws_content_delivery_bucket": "taxidi.tech",
    "aws_content_delivery_bucket_region": "ap-southeast-2",
    "aws_content_delivery_url": "https://d95fuc5xjx7o.cloudfront.net"
};


export default awsmobile;
